exports.LEAGUE_IDS_NAMES = [
  {
    id: 0,
    name: "Select your league"
  },
  {
    id: 8,
    name: "Premiere League (England)",
    clubs: [
      {name: 'Arsenal'},
      {name: 'Bournemouth'},
      {name: 'Brighton & Hove Albion'},
      {name: 'Burnley'},
      {name: 'Chelsea'},
      {name: 'Crystal Palace'},
      {name: 'Everton'},
      {name: 'Huddersfield Town'},
      {name: 'Leicester City'},
      {name: 'Liverpool'},
      {name: 'Manchester City'},
      {name: 'Manchester United'},
      {name: 'Newcastle United'},
      {name: 'Southampton'},
      {name: 'Stoke City'},
      {name: 'Swansea City'},
      {name: 'Tottenham Hotspur'},
      {name: 'Watford'},
      {name: 'West Bromwich Albion'},
      {name: 'West Ham United'} 
    ]
  },
  {
    id:9, 
    name: "Championship (England)",
    clubs: [
      {name: 'Aston Villa'},
      {name: 'Barnsley'},
      {name: 'Birmingham City'},
      {name: 'Bolton Wanderers'},
      {name: 'Brentford'},
      {name: 'Bristol City'},
      {name: 'Burton Albion'},
      {name: 'Cardiff City'},
      {name: 'Derby County'},
      {name: 'Fulham'},
      {name: 'Hull City'},
      {name: 'Ipswich Town'},
      {name: 'Leeds United'},
      {name: 'Middlesbrough'},
      {name: 'Millwall'},
      {name: 'Norwich City'},
      {name: 'Nottingham Forest'},
      {name: 'Preston North End'},
      {name: 'Queens Park Rangers'},
      {name: 'Reading'},
      {name: 'Sheffield United'},
      {name: 'Sheffield Wednesday'},
      {name: 'Sunderland'},
      {name: 'Wolverhampton Wanderers'}
    ]
  },
  {
    id: 12, 
    name: "League One (England)",
    clubs: [
      {name: 'AFC Wimbledon'},
      {name: 'Blackburn Rovers'},
      {name: 'Blackpool'},
      {name: 'Bradford City'},
      {name: 'Bristol Rovers'},
      {name: 'Bury'},
      {name: 'Charlton Athletic'},
      {name: 'Doncaster Rovers'},
      {name: 'Fleetwood Town'},
      {name: 'Gillingham'},
      {name: 'Milton Keynes Dons'},
      {name: 'Northampton Town'},
      {name: 'Oldham Athletic'},
      {name: 'Oxford United'},
      {name: 'Peterborough United'},
      {name: 'Plymouth Argyle'},
      {name: 'Portsmouth'},
      {name: 'Rochdale'},
      {name: 'Rotherham United'},
      {name: 'Scrunthorpe United'},
      {name: 'Shrewsbury Town'},
      {name: 'Southend United'},
      {name: 'Walsall'},
      {name: 'Wigan Athletic'}
    ]
  },
  {
    id: 14, 
    name: "League Two (England)",
    clubs: [
      {name: 'Accrington Stanley'},
      {name: 'Barnet'},
      {name: 'Cambridge United'},
      {name: 'Carlisle United'},
      {name: 'Cheltenham Town'},
      {name: 'Chesterfield'},
      {name: 'Colchester United'},
      {name: 'Crawley Town'},
      {name: 'Crewe Alexandria'},
      {name: 'Exeter City'},
      {name: 'Forest Green Rovers'},
      {name: 'Grimsby Town'},
      {name: 'Lincoln City'},
      {name: 'Luton Town'},
      {name: 'Mansfield Town'},
      {name: 'Morecambe'},
      {name: 'Newport County'},
      {name: 'Notts County'},
      {name: 'Port Vale'},
      {name: 'Stevenage'},
      {name: 'Swindon Town'},
      {name: 'Wycombe Wanderers'},
      {name: 'Yeovil Town'}
    ]
  },
  {
    id: 72, 
    name: "Eredivise (Netherlands)",
    clubs: [ 
      {name: 'ADO Den Haag'},
      {name: 'Ajax'},
      {name: 'AZ'},
      {name: 'Excelsior'},
      {name: 'Feyenoord'},
      {name: 'Groningen'},
      {name: 'Heerenveen'},
      {name: 'Heracles Almelo'},
      {name: 'NAC Breda'},
      {name: 'PEC Zwolle'},
      {name: 'PSV'},
      {name: 'Roda JC'},
      {name: 'Sparta Rotterdam'},
      {name: 'Twente'},
      {name: 'Utrecht'},
      {name: 'Vitesse'},
      {name: 'VVV-Venlo'},
      {name: 'Willem II'}
    ]
  },
  {
    id: 74, 
    name: "Eerste Divisie (Netherlands)",
    clubs: [
      {name: 'Jong Ajax'},
      {name: 'Almere City'},
      {name: 'Jong AZ'},
      {name: 'Cambuur'},
      {name: 'De Graafschap'},
      {name: 'Den Bosch'},
      {name: 'Dordrecht'},
      {name: 'FC Eindhoven'},
      {name: 'Emmen'},
      {name: 'Fortuna Sittard'},
      {name: 'Go Ahead Eagles'},
      {name: 'Helmond Sport'},
      {name: 'MVV'},
      {name: 'NEC'},
      {name: 'Oss'},
      {name: 'Jong PSV'},
      {name: 'RKC Waalwijk'},
      {name: 'Telstar'},
      {name: 'Jong FC Utrect'},
      {name: 'Volendam'}
    ]
  },
  {
    id: 82, 
    name: "Bundesliga (Germany)",
    clubs: [
      {name: 'FC Augsburg'},
      {name: 'Hertha BSC'},
      {name: 'Weder Bremen'},
      {name: 'Borussia Dortmund'},
      {name: 'Eintracht Frankfurt'},
      {name: 'SC Freiburg'},
      {name: 'Hamburger SV'},
      {name: 'Hannover 96'},
      {name: '1899 Hoffenheim'},
      {name: '1. FC Köln'},
      {name: 'RB Leipzig'},
      {name: 'Bayer Leverkusen'},
      {name: 'Mainz 05'},
      {name: 'Borussia Mönchengladbach'},
      {name: 'Bayern Munich'},
      {name: 'Schalke 04'},
      {name: 'VfB Stuttgart'},
      {name: 'VfL Wolfsburg'}
    ]
  },
  {
    id: 85, 
    name: "2.Bundesliga (Germany)",
    clubs: [
      {name: 'Erzgebirge Aue'},
      {name: 'Arminia Bielefeld'},
      {name: 'VfL Bochum'},
      {name: 'Eintracht Braunschweig'},
      {name: 'Darmstadt 98'},
      {name: 'Dynamo Dresden'},
      {name: 'MSV Duisburg'},
      {name: 'Fortuna Düsseldorf'},
      {name: 'SpVgg Greuther Fürth'},
      {name: '1. FC Heidenheim'},
      {name: 'FC Ingolstadt'},
      {name: '1. FC Kaiserslautern'},
      {name: 'Holstein Kiel'},
      {name: '1. FC Nürnberg'},
      {name: 'Jahn Regensburg'},
      {name: 'SV Sandhausen'},
      {name: 'FC St. Pauli'},
      {name: 'Union Berlin'}
    ]
  },
  {
    id: 181, 
    name: "Bundesliga (Austria)",
    clubs: [
      {name: 'Admira Wacker Mödling'},
      {name: 'Austria Wien'},
      {name: 'LASK Linz'},
      {name: 'Rapid Wien'},
      {name: 'Red Bull Salzburg'},
      {name: 'Rheindorf Altach'},
      {name: 'St. Pölten'},
      {name: 'Sturm Graz'},
      {name: 'SV Mattersburg'},
      {name: 'Wolfsberger AC'}
    ]
  },
  {
    id: 208, 
    name: "First Division A (Belgium)",
    clubs: [
      {name: 'Anderlecht'},
      {name: 'Antwerp'},
      {name: 'Charleroi'},
      {name: 'Club Brugge'},
      {name: 'Eupen'},
      {name: 'Genk'},
      {name: 'Gent'},
      {name: 'Kortrijk'},
      {name: 'Lokeren'},
      {name: 'Mechelen'},
      {name: 'Excel Mouscron'},
      {name: 'Oostende'},
      {name: 'Sint-Truiden'},
      {name: 'Standard Liège'},
      {name: 'Waasland-Beveren'},
      {name: 'Zulte Waregem'}
    ]
  },
  {
    id: 271, 
    name: "Superliga (Denmark)",
    clubs: [
      {name: 'AaB'},
      {name: 'AGF'},
      {name: 'Brøndby'},
      {name: 'FCK'},
      {name: 'Helsingør'},
      {name: 'Hobro'},
      {name: 'Horsens'},
      {name: 'Midtjylland'},
      {name: 'Nordsjælland'},
      {name: 'Lyngby'},
      {name: 'OB'},
      {name: 'Randers'},
      {name: 'Silkeborg IF'},
      {name: 'SønderjyskE'}
    ]
  },
  {
    id: 301, 
    name: "Ligue 1 (France)",
    clubs: [
      {name: 'Amiens'},
      {name: 'Angers'},
      {name: 'Bordeaux'},
      {name: 'Caen'},
      {name: 'Dijon'},
      {name: 'Guingamp'},
      {name: 'Lille'},
      {name: 'Lyon'},
      {name: 'Marseille'},
      {name: 'Metz'},
      {name: 'Monaco'},
      {name: 'Montpellier'},
      {name: 'Nantes'},
      {name: 'Nice'},
      {name: 'PSG'},
      {name: 'Rennes'},
      {name: 'Saint-Étienne'},
      {name: 'Strasbourg'},
      {name: 'Toulouse'},
      {name: 'Troyes'}
    ]
  },
  {
    id: 304, 
    name: "Ligue 2 (France)",
    clubs: [
      {name: 'AC Ajaccio'},
      {name: 'Auxerre'},
      {name: 'Bourg-Péronnas'},
      {name: 'Brest'},
      {name: 'Châteauroux'},
      {name: 'Clermont Foot'},
      {name: 'Gazélec Ajaccio'},
      {name: 'Le Havre'},
      {name: 'Lens'},
      {name: 'Lorient'},
      {name: 'Nancy'},
      {name: 'Nîmes'},
      {name: 'Niort'},
      {name: 'Orléans'},
      {name: 'Paris FC'},
      {name: 'Quevilly-Rouen'},
      {name: 'Reims'},
      {name: 'Sochaux'},
      {name: 'Tours'},
      {name: 'Valenciennes'}
    ]
  },
  {
    id: 325, 
    name: "Superleague (Greece)",
    clubs: [
      {name: 'AEK Athens'},
      {name: 'AEL'},
      {name: 'Apollon Smyrni'},
      {name: 'Asteras Tripoli'},
      {name: 'Atromitos'},
      {name: 'Kerkyra'},
      {name: 'Lamia'},
      {name: 'Levadiakos'},
      {name: 'Olympiacos'},
      {name: 'Panathinaikos'},
      {name: 'Panetolikos'},
      {name: 'Panionios'},
      {name: 'PAOK'},
      {name: 'PAS Giannina'},
      {name: 'Platanias'},
      {name: 'Xanthi'}
    ]
  },
  {
    id: 345, 
    name: "Úrvalsdeild (Iceland)",
    clubs: [
      {name: 'Breiðablik'},
      {name: 'FH'},
      {name: 'Fjölnir'},
      {name: 'Grindavík'},
      {name: 'ÍA'},
      {name: 'ÍBV'},
      {name: 'KA'},
      {name: 'KR'},
      {name: 'Stjarnan'},
      {name: 'Valur'},
      {name: 'Víkingur Ó.'},
      {name: 'Víkingur R.'}
    ]
  },
  {
    id: 360, 
    name: "Premiere Division (Ireland)",
    clubs: [
      {name: "Bohemians"},
      {name: "Bray Wanderers"},
      {name: "Cork City"},
      {name: "Derry City"},
      {name: "Dundalk"},
      {name: "Limerick"},
      {name: "Shamrock Rovers"},
      {name: "Sligo Rovers"},
      {name: "St Patrick's Athletic"},
      {name: "Waterford"}
    ]
  },
  {
    id: 384, 
    name: "Serie A (Italy)",
    clubs: [
      {name: 'Atalanta'},
      {name: 'Benevento'},
      {name: 'Bologna'},
      {name: 'Cagliari'},
      {name: 'Chievo'},
      {name: 'Crotone'},
      {name: 'Fiorentina'},
      {name: 'Genoa'},
      {name: 'Hellas Verona'},
      {name: 'Internazionale'},
      {name: 'Juventus'},
      {name: 'Lazio'},
      {name: 'Milan'},
      {name: 'Napoli'},
      {name: 'Roma'},
      {name: 'Sampdoria'},
      {name: 'Sassuolo'},
      {name: 'SPAL'},
      {name: 'Torino'},
      {name: 'Udinese'}
    ]
  },
  {
    id: 387, 
    name: "Serie B (Italy)",
    clubs: [ 
    ]
  },
  {
    id: 438, 
    name: "Premiership (Northern Ireland)",
    clubs: [
      {name: 'Ards'},
      {name: 'Ballinamallard United'},
      {name: 'Ballymena United'},
      {name: 'Carrick Rangers'},
      {name: 'Cliftonville'},
      {name: 'Coleraine'},
      {name: 'Crusaders'},
      {name: 'Dungannon Swifts'},
      {name: 'Glenavon'},
      {name: 'Glentoran'},
      {name: 'Linfield'},
      {name: 'Warrenpoint Town'}
    ]
  },
  {
    id: 444, 
    name: "Eliteserien (Norway)",
    clubs: [
      {name: 'Bodø/Glimt'},
      {name: 'Brann'},
      {name: 'Haugesund'},
      {name: 'Kristiansund'},
      {name: 'Lillestrøm'},
      {name: 'Molde'},
      {name: 'Odd'},
      {name: 'Ranheim'},
      {name: 'Rosenborg'},
      {name: 'Sandefjord'},
      {name: 'Sarpsborg 08'},
      {name: 'Stabæk'},
      {name: 'Start'},
      {name: 'Strømsgodset'},
      {name: 'Tromsø'},
      {name: 'Vålerenga'}
    ]
  },
  {
    id: 453, 
    name: "Ekstraklasa (Poland)",
    clubs: [
      {name: 'Arka Gdynia'},
      {name: 'Bruk-Bet Termalica Nieciecza'},
      {name: 'Cracovia'},
      {name: 'Górnik Zabrze'},
      {name: 'Jagiellonia Białystok'},
      {name: 'Korona Kielce'},
      {name: 'Lech Poznań'},
      {name: 'Lechia Gdańsk'},
      {name: 'Legia Warsaw'},
      {name: 'Piast Gliwice'},
      {name: 'Pogoń Szczecin'},
      {name: 'Sandecja Nowy Sącz'},
      {name: 'Śląsk Wrocław'},
      {name: 'Wisła Kraków'},
      {name: 'Wisła Płock'},
      {name: 'Zagłębie Lubin'}
    ]
  },
  {
    id: 462, 
    name: "Primeira Liga (Portugal)",
    clubs: [
      {name: 'Belenenses'},
      {name: 'Benfica'},
      {name: 'Boavista'},
      {name: 'Braga'},
      {name: 'Chaves'},
      {name: 'Desportivo das Aves'},
      {name: 'Estoril'},
      {name: 'Feirense'},
      {name: 'Marítimo'},
      {name: 'Moreirense'},
      {name: 'Paços de Ferreira'},
      {name: 'Porto'},
      {name: 'Portimonense'},
      {name: 'Rio Ave'},
      {name: 'Sporting CP'},
      {name: 'Tondela'},
      {name: 'Vitória de Guimarães'},
      {name: 'Vitória de Setúbal'}
    ]
  },
  {
    id: 486, 
    name: "Premiere League (Russia)",
    clubs: [
      {name: 'Akhmat'},
      {name: 'Amkar'},
      {name: 'Anzhi'},
      {name: 'Arsenal'},
      {name: 'CSKA'},
      {name: 'Dynamo'},
      {name: 'Krasnodar'},
      {name: 'Lokomotiv'},
      {name: 'Rostov'},
      {name: 'Rubin'},
      {name: 'SKA-Khabarovsk'},
      {name: 'Spartak'},
      {name: 'Tosno'},
      {name: 'Ufa'},
      {name: 'Ural'},
      {name: 'Zenit'}
    ]
  },
  {
    id: 501, 
    name: "Premiership (Scotland)",
    clubs: [
      {name: 'Aberdeen'},
      {name: 'Celtic'},
      {name: 'Dundee'},
      {name: 'Hamilton Academical'},
      {name: 'Heart of Midlothian'},
      {name: 'Hibernian'},
      {name: 'Kilmarnock'},
      {name: 'Motherwell'},
      {name: 'Partick Thistle'},
      {name: 'Rangers'},
      {name: 'Ross County'},
      {name: 'St Johnstone'}
    ]
  },
  {
    id: 504, 
    name: "Championship (Scotland)",
    clubs: [
      {name: 'Brechin City'},
      {name: 'Dumbarton'},
      {name: 'Dundee United'},
      {name: 'Dunfermline Athletic'},
      {name: 'Falkirk'},
      {name: 'Greenock Morton'},
      {name: 'Inverness Caledonian Thistle'},
      {name: 'Livingston'},
      {name: 'Queen of the South'},
      {name: 'St Mirren'}
    ]
  },
  {
    id: 564, 
    name: "La Liga (Spain)",
    clubs: [
      {name: 'Alavés'},
      {name: 'Athletic Bilbao'},
      {name: 'Atlético Madrid'},
      {name: 'Barcelona'},
      {name: 'Celta Vigo'},
      {name: 'Deportivo La Coruña'},
      {name: 'Eibar'},
      {name: 'Espanyol'},
      {name: 'Getafe'},
      {name: 'Girona'},
      {name: 'Las Palmas'},
      {name: 'Leganés'},
      {name: 'Levante'},
      {name: 'Málaga'},
      {name: 'Real Betis'},
      {name: 'Real Madrid'},
      {name: 'Real Sociedad'},
      {name: 'Sevilla'},
      {name: 'Valencia'},
      {name: 'Villarreal'}
    ]
  },
  {
    id: 567, 
    name: "Segunda Division (Spain)",
    clubs: [
      {name: 'Albacete'},
      {name: 'Alcorcón'},
      {name: 'Almería'},
      {name: 'Barcelona B'},
      {name: 'Cádiz'},
      {name: 'Córdoba'},
      {name: 'Cultural Leonesa'},
      {name: 'Gimnàstic'},
      {name: 'Granada'},
      {name: 'Huesca'},
      {name: 'Lorca FC'},
      {name: 'Lugo'},
      {name: 'Numancia'},
      {name: 'Osasuna'},
      {name: 'Oviedo'},
      {name: 'Rayo Vallecano'},
      {name: 'Reus'},
      {name: 'Sevilla Atlético'},
      {name: 'Sporting Gijón'},
      {name: 'Tenerife'},
      {name: 'Valladolid'},
      {name: 'Zaragoza'}
    ]
  },
  {
    id: 573, 
    name: "Allsvenskan (Sweden)",
    clubs: [
      {name: 'AFC Eskilstuna'},
      {name: 'AIK'},
      {name: 'BK Häcken'},
      {name: 'Djurgårdens IF'},
      {name: 'GIF Sundsvall'},
      {name: 'Halmstads BK'},
      {name: 'Hammarby IF'},
      {name: 'IF Elfsborg'},
      {name: 'IFK Göteborg'},
      {name: 'IFK Norrköping'},
      {name: 'IK Sirius'},
      {name: 'Jönköpings Södra IF'},
      {name: 'Kalmar FF'},
      {name: 'Malmö FF'},
      {name: 'Örebro SK'},
      {name: 'Östersunds FK'}
    ]
  },
  {
    id: 579, 
    name: "Superettan (Sweden)",
    clubs: [
      {name: 'Dalkurd'},
      {name: 'Degerfors'},
      {name: 'Falkenberg'},
      {name: 'GAIS'},
      {name: 'Gefle'},
      {name: 'Helsingborg'},
      {name: 'Brommapojkarna'},
      {name: 'Värnamo'},
      {name: 'Frej'},
      {name: 'Norrby'},
      {name: 'Syrianska'},
      {name: 'Trelleborg'},
      {name: 'Varberg'},
      {name: 'Åtvidaberg'},
      {name: 'Örgryte'},
      {name: 'Öster'}
    ]
  },
  {
    id: 591, 
    name: "Super League (Switzerland)",
    clubs: [
      {name: 'Basel'},
      {name: 'Grasshopper'},
      {name: 'Lausanne'},
      {name: 'Lugano'},
      {name: 'Luzern'},
      {name: 'Sion'},
      {name: 'St. Gallen'},
      {name: 'Thun'},
      {name: 'Young Boys'},
      {name: 'FC Zürich'}
    ]
  },
  {
    id: 600, 
    name: "Süper Lig (Turkey)",
    clubs: [
      {name: 'Akhisar Belediyespor'},
      {name: 'Alanyaspor'},
      {name: 'Antalyaspor'},
      {name: 'Beşiktaş'},
      {name: 'Bursaspor'},
      {name: 'Fenerbahçe'},
      {name: 'Galatasaray'},
      {name: 'Gençlerbirliği'},
      {name: 'Göztepe'},
      {name: 'İstanbul Başakşehir'},
      {name: 'Kardemir Karabükspor'},
      {name: 'Kasımpaşa'},
      {name: 'Kayserispor'},
      {name: 'Konyaspor'},
      {name: 'Osmanlıspor'},
      {name: 'Sivasspor'},
      {name: 'Trabzonspor'},
      {name: 'Yeni Malatyaspor'}
    ]
  },
  {
    id: 624, 
    name: "Premiere League (Wales)",
    clubs: [
      {name: "Aberystwyth Town"},
      {name: "Bala Town"},
      {name: "Bangor City"},
      {name: "Barry Town United"},
      {name: "Cardiff Metropolitan University"},
      {name: "Carmarthen Town"},
      {name: "Cefn Druids"},
      {name: "Connah's Quay Nomads"},
      {name: "Llandudno"},
      {name: "Newtown"},
      {name: "Prestatyn Town"},
      {name: "The New Saints"}
    ]
  },
  {
    id: 636, 
    name: "Primera Division (Argentina)",
    clubs: [
      {name: "Argentinos Juniors"},
      {name: "Arsenal"},
      {name: "Atlético Tucumán"},
      {name: "Banfield"},
      {name: "Belgrano"},
      {name: "Boca Juniors"},
      {name: "Chacarita Juniors"},
      {name: "Colón"},
      {name: "Defensa y Justicia"},
      {name: "Estudiantes (LP)"},
      {name: "Gimnasia y Esgrima (LP)"},
      {name: "Godoy Cruz"},
      {name: "Huracán"},
      {name: "Independiente"},
      {name: "Lanús"},
      {name: "Newell's Old Boys"},
      {name: "Olimpo"},
      {name: "Patronato"},
      {name: "Racing"},
      {name: "River Plate"},
      {name: "Rosario Central"},
      {name: "San Lorenzo"},
      {name: "San Martín (SJ)"},
      {name: "Talleres (C)"},
      {name: "Temperley"},
      {name: "Tigre"},
      {name: "Unión"},
      {name: "Vélez Sarsfield"}
    ]
  },
  {
    id: 639, 
    name: "Primera B (Argentina)",
    clubs: [
      {name: 'Agropecuario Argentino'},
      {name: 'Aldosivi'},
      {name: 'All Boys'},
      {name: 'Almagro'},
      {name: 'Atlético de Rafaela'},
      {name: 'Boca Unidos'},
      {name: 'Brown'},
      {name: 'Deportivo Morón'},
      {name: 'Deportivo Riestra'},
      {name: 'Estudiantes (SL)'},
      {name: 'Ferro Carril Oeste'},
      {name: 'Flandria'},
      {name: 'Gimnasia y Esgrima (J)'},
      {name: 'Guillermo Brown'},
      {name: 'Independiente Rivadavia'},
      {name: 'Instituto'},
      {name: 'Juventud Unida (G)'},
      {name: 'Los Andes'},
      {name: 'Mitre (SdE)'},
      {name: 'Nueva Chicago'},
      {name: 'Quilmes'},
      {name: 'San Martín (T)'},
      {name: 'Santamarina'},
      {name: 'Sarmiento (J)'},
      {name: 'Villa Dálmine'}
    ]
  },
  {
    id: 648, 
    name: "Serie A (Brazil)",
    clubs: [
      {name: 'América Mineiro'},
      {name: 'Atlético Mineiro'},
      {name: 'Atlético Paranaense'},
      {name: 'Bahia'},
      {name: 'Botafogo'},
      {name: 'Ceará'},
      {name: 'Chapecoense'},
      {name: 'Corinthians'},
      {name: 'Cruzeiro'},
      {name: 'Flamengo'},
      {name: 'Fluminense'},
      {name: 'Grêmio'},
      {name: 'Internacional'},
      {name: 'Palmeiras'},
      {name: 'Paraná'},
      {name: 'Santos'},
      {name: 'São Paulo'},
      {name: 'Sport'},
      {name: 'Vasco da Gama'},
      {name: 'Vitória'}
    ]
  },
  {
    id: 651, 
    name: "Serie B (Brazil)",
    clubs: [
      {name: 'Atlético Goianiense'},
      {name: 'Avaí'},
      {name: 'Boa Esporte'},
      {name: 'Brasil de Pelotas'},
      {name: 'Coritiba'},
      {name: 'CRB'},
      {name: 'Criciúma'},
      {name: 'CSA'},
      {name: 'Figueirense'},
      {name: 'Fortaleza'},
      {name: 'Goiás'},
      {name: 'Guarani'},
      {name: 'Juventude'},
      {name: 'Londrina'},
      {name: 'Oeste'},
      {name: 'Paysandu'},
      {name: 'Ponte Preta'},
      {name: 'Sampaio Corrêa'},
      {name: 'São Bento'},
      {name: 'Vila Nova'}
    ]
  },
  {
    id: 663, 
    name: "Primera Division (Chile)",
    clubs: [
      {name: "Audax Italiano"},
      {name: "Colo-Colo"},
      {name: "Curicó Unido"},
      {name: "Deportes Antofagasta"},
      {name: "Deportes Iquique"},
      {name: "Deportes Temuco"},
      {name: "Everton"},
      {name: "Huachipato"},
      {name: "O'Higgins"},
      {name: "Palestino"},
      {name: "San Luis"},
      {name: "Unión Española"},
      {name: "Unión La Calera"},
      {name: "Universidad Católica"},
      {name: "Universidad de Chile"},
      {name: "Universidad de Concepción"}
    ]
  },
  {
    id: 672, 
    name: "Primera A (Colombia)",
    clubs: [
      {name: "Alianza Petrolera"},
      {name: "América de Cali"},
      {name: "Atlético Bucaramanga"},
      {name: "Atlético Huila"},
      {name: "Atlético Nacional"},
      {name: "Boyacá Chicó"},
      {name: "Deportes Tolima"},
      {name: "Deportivo Cali"},
      {name: "Deportivo Pasto"},
      {name: "Envigado"},
      {name: "Independiente Medellín"},
      {name: "Jaguares"},
      {name: "Junior"},
      {name: "La Equidad"},
      {name: "Leones"},
      {name: "Millonarios"},
      {name: "Once Caldas"},
      {name: "Patriotas"},
      {name: "Rionegro Águilas"},
      {name: "Santa Fe"}
    ]
  },
  {
    id: 696, 
    name: "Primera A (Ecuador)",
    clubs: [
      {name: 'Aucas'},
      {name: 'Barcelona'},
      {name: 'Delfín'},
      {name: 'Deportivo Cuenca'},
      {name: 'El Nacional'},
      {name: 'Emelec'},
      {name: 'Guayaquil City'},
      {name: 'Independiente del Valle'},
      {name: 'LDU Quito'},
      {name: 'Macará'},
      {name: 'Técnico Universitario'},
      {name: 'Universidad Católica'}
    ]
  },
  {
    id: 743, 
    name: "Liga MX (Mexico)",
    clubs: [
      {name: 'América'},
      {name: 'Atlas'},
      {name: 'BUAP'},
      {name: 'Cruz Azul'},
      {name: 'Guadalajara'},
      {name: 'León'},
      {name: 'Monterrey'},
      {name: 'Morelia'},
      {name: 'Necaxa'},
      {name: 'Pachuca'},
      {name: 'Puebla'},
      {name: 'Querétaro'},
      {name: 'Santos Laguna'},
      {name: 'Tijuana'},
      {name: 'Toluca'},
      {name: 'UANL'},
      {name: 'UNAM'},
      {name: 'Veracruz'}
    ]
  },
  {
    id: 779, 
    name: "Major League Soccer (USA)",
    clubs: [
      {name: 'Atlanta United'},
      {name: 'Chicago Fire'},
      {name: 'Colorado Rapids'},
      {name: 'Columbus Crew'},
      {name: 'DC United'},
      {name: 'Dallas'},
      {name: 'Houston Dynamo'},
      {name: 'LA Galaxy'},
      {name: 'Los Angeles'},
      {name: 'Minnesota United'},
      {name: 'Montreal Impact'},
      {name: 'New England'},
      {name: 'New York City'},
      {name: 'New York RB'},
      {name: 'Orlando City'},
      {name: 'Philadelphia Union'},
      {name: 'Portland Timbers'},
      {name: 'Real Salt Lake'},
      {name: 'SJ Earthquakes'},
      {name: 'Seattle Sounders'},
      {name: 'Sporting KC'},
      {name: 'Toronto'},
      {name: 'Vancouver Whitecaps'}
    ]
  },
  {
    id: 968, 
    name: "J-League (Japan)",
    clubs: [
      {name: 'Hokkaido Consadole Sapporo'},
      {name: 'Vegalta Sendai'},
      {name: 'Kashima Antlers'},
      {name: 'Urawa Red Diamonds'},
      {name: 'Kashiwa Reysol'},
      {name: 'FC Tokyo'},
      {name: 'Kawasaki Frontale'},
      {name: 'Yokohama F. Marinos'},
      {name: 'Shonan Bellmare'},
      {name: 'Shimizu S-Pulse'},
      {name: 'Júbilo Iwata'},
      {name: 'Nagoya Grampus'},
      {name: 'Gamba Osaka'},
      {name: 'Cerezo Osaka'},
      {name: 'Vissel Kobe'},
      {name: 'Sanfrecce Hiroshima'},
      {name: 'Sagan Tosu'},
      {name: 'V-Varen Nagasaki'}
    ]
  },
  {
    id: 989, 
    name: "Super League (China)",
    clubs: [
      {name: 'Guangzhou Evergrande Taobao'},
      {name: 'Shanghai SIPG'},
      {name: 'Tianjin Quanjian'},
      {name: 'Hebei China Fortune'},
      {name: 'Guangzhou R&F'},
      {name: 'Shandong Luneng Taishan'},
      {name: 'Changchun Yatai'},
      {name: 'Guizhou Hengfeng'},
      {name: 'Beijing Sinobo Guoan'},
      {name: 'Chongqing Dangdai Lifan'},
      {name: 'Shanghai Greenland Shenhua'},
      {name: 'Jiangsu Suning'},
      {name: 'Tianjin Teda'},
      {name: 'Henan Jianye'},
      {name: 'Dalian Yifang'},
      {name: 'Beijing Renhe'}
    ]
  },
  {
    id: 1007, 
    name: "Indian Super League (India)",
    clubs: [
      {name: 'ATK'},
      {name: 'Bengaluru'},
      {name: 'Chennaiyin'},
      {name: 'Delhi Dynamos'},
      {name: 'Goa'},
      {name: 'Jamshedpur'},
      {name: 'Kerala Blasters'},
      {name: 'Mumbai City'},
      {name: 'NorthEast United'},
      {name: 'Pune City'}
    ]
  },
  {
    id: 1098, 
    name: "Liga de Futbol Profesional (Bolivia)",
    clubs: [
      {name: 'Aurora'},
      {name: 'Blooming'},
      {name: 'Bolívar'},
      {name: 'Destroyers'},
      {name: 'Guabirá'},
      {name: 'Jorge Wilstermann'},
      {name: 'Nacional Potosí'},
      {name: 'Oriente Petrolero'},
      {name: 'Real Potosí'},
      {name: 'Royal Pari'},
      {name: 'San José'},
      {name: 'Sport Boys'},
      {name: 'The Strongest'},
      {name: 'Universitario'}
    ]
  },
  {
    id: 1356, 
    name: "A-League (Australia)",
    clubs: [
      {name: 'Adelaide United'},
      {name: 'Brisbane Roar'},
      {name: 'Central Coast Mariners'},
      {name: 'Melbourne City'},
      {name: 'Melbourne Victory'},
      {name: 'Newcastle Jets'},
      {name: 'Perth Glory'},
      {name: 'Sydney FC'},
      {name: 'Wellington Phoenix'},
      {name: 'Western Sydney Wanderers'}
    ]
  }
];