exports.LEAGUE_IDS_NAMES = [
  [8, "Premiere League (England)"],
  [9, "Championship (England)"],
  [12, "League One (England)"],
  [14, "League Two (England)"],
  [72, "Eredivise (Netherlands)"],
  [74, "Eerste Divisie (Netherlands)"],
  [82, "Bundesliga (Germany)"],
  [85, "2.Bundesliga (Germany)"],
  [181, "Bundesliga (Austria)"],
  [208, "Jupiler Pro League (Belgium)"],
  [271, "Superliga (Denmark)"],
  [301, "Ligue 1 (France)"],
  [304, "Ligue 2 (France)"],
  [325, "Super League (Greece)"],
  [345, "Urvalsdeild (Iceland)"],
  [360, "Premiere Division (Ireland)"],
  [384, "Serie A (Italy)"],
  [387, "Serie B (Italy)"],
  [438, "Premiership (Northern Ireland)"],
  [444, "Tippeligaen (Norway)"],
  [453, "Ekstraklasa (Poland)"],
  [462, "Primeira Liga (Portugal)"],
  [486, "Premiere League (Russia)"],
  [501, "Premiership (Scotland)"],
  [504, "Championship (Scotland)"],
  [564, "La Liga (Spain)"],
  [567, "Segunda Division (Spain)"],
  [573, "Allsvenskan (Sweden)"],
  [579, "Superettan (Sweden)"],
  [591, "Super League (Switzerland)"],
  [600, "Super Lig (Turkey)"],
  [624, "Premiere League (Wales)"],
  [636, "Primera Division (Argentina)"],
  [639, "Primera B (Argentina)"],
  [648, "Serie A (Brazil)"],
  [651, "Serie B (Brazil)"],
  [663, "Primera Division (Chile)"],
  [672, "Primera A: Apertura (Colombia)"],
  [675, "Primera A: Clausura (Colombia)"],
  [693, "Primera A: Apertura (Ecuador)"],
  [696, "Primera A: Clausura (Ecuador)"],
  [743, "Liga MX (Mexico)"],
  [779, "Major League Soccer (USA)"],
  [968, "J-League (Japan)"],
  [989, "Super League (China)"],
  [1007, "Indian Super League (India)"],
  [1098, "Liga de Futbol Profesional (Bolivia)"],
  [1356, "A-League (Australia)"]
];