const mongoose = require('mongoose'),
	Schema = mongoose.Schema,

	fantasyScheduleSchema = Schema({
		matches: [[{type: Schema.Types.ObjectId, ref: 'FantasyMatch'}], [{type: Schema.Types.ObjectId, ref: 'FantasyMatch'}], [{type: Schema.Types.ObjectId, ref: 'FantasyMatch'}], [{type: Schema.Types.ObjectId, ref: 'FantasyMatch'}], [{type: Schema.Types.ObjectId, ref: 'FantasyMatch'}], [{type: Schema.Types.ObjectId, ref: 'FantasyMatch'}], [{type: Schema.Types.ObjectId, ref: 'FantasyMatch'}], [{type: Schema.Types.ObjectId, ref: 'FantasyMatch'}], [{type: Schema.Types.ObjectId, ref: 'FantasyMatch'}], [{type: Schema.Types.ObjectId, ref: 'FantasyMatch'}], [{type: Schema.Types.ObjectId, ref: 'FantasyMatch'}], [{type: Schema.Types.ObjectId, ref: 'FantasyMatch'}], [{type: Schema.Types.ObjectId, ref: 'FantasyMatch'}], [{type: Schema.Types.ObjectId, ref: 'FantasyMatch'}], [{type: Schema.Types.ObjectId, ref: 'FantasyMatch'}], [{type: Schema.Types.ObjectId, ref: 'FantasyMatch'}], [{type: Schema.Types.ObjectId, ref: 'FantasyMatch'}], [{type: Schema.Types.ObjectId, ref: 'FantasyMatch'}], [{type: Schema.Types.ObjectId, ref: 'FantasyMatch'}], [{type: Schema.Types.ObjectId, ref: 'FantasyMatch'}], [{type: Schema.Types.ObjectId, ref: 'FantasyMatch'}], [{type: Schema.Types.ObjectId, ref: 'FantasyMatch'}], [{type: Schema.Types.ObjectId, ref: 'FantasyMatch'}], [{type: Schema.Types.ObjectId, ref: 'FantasyMatch'}], [{type: Schema.Types.ObjectId, ref: 'FantasyMatch'}], [{type: Schema.Types.ObjectId, ref: 'FantasyMatch'}], [{type: Schema.Types.ObjectId, ref: 'FantasyMatch'}], [{type: Schema.Types.ObjectId, ref: 'FantasyMatch'}], [{type: Schema.Types.ObjectId, ref: 'FantasyMatch'}], [{type: Schema.Types.ObjectId, ref: 'FantasyMatch'}], [{type: Schema.Types.ObjectId, ref: 'FantasyMatch'}], [{type: Schema.Types.ObjectId, ref: 'FantasyMatch'}], [{type: Schema.Types.ObjectId, ref: 'FantasyMatch'}], [{type: Schema.Types.ObjectId, ref: 'FantasyMatch'}], [{type: Schema.Types.ObjectId, ref: 'FantasyMatch'}], [{type: Schema.Types.ObjectId, ref: 'FantasyMatch'}], [{type: Schema.Types.ObjectId, ref: 'FantasyMatch'}], [{type: Schema.Types.ObjectId, ref: 'FantasyMatch'}]] // 38 total weeks of matches are represented here
	}),

	FantasySchedule = mongoose.model('FantasySchedule', fantasyScheduleSchema);

module.exports = FantasySchedule;